package io.github.stainlessstasis.config;

public record MessageTemplates (
        String[] comment,
        String fullSpawnMessage,
        String despawnMessage,
        String despawnReason_Despawned,
        String despawnReason_Captured,
        String despawnReason_Fainted,
        String despawnReason_Died,
        String shiny,
        String shiny_unformatted,
        String level,
        String level_hover,
        String level_unformatted,
        String ivs,
        String ivs_hover,
        String ivs_unformatted,
        String evs,
        String evs_hover,
        String evs_unformatted,
        String nature,
        String nature_hover,
        String nature_unformatted,
        String ability,
        String ability_hover,
        String ability_unformatted,
        String gender,
        String gender_hover,
        String gender_unformatted,
        String male,
        String female,
        String genderless,
        String coords,
        String coords_hover,
        String coords_unformatted,
        String biome,
        String biome_hover,
        String biome_unformatted,
        String nearest_player,
        String nearest_player_hover,
        String nearest_player_unformatted,
        String legendary,
        String legendary_unformatted,
        String mythical,
        String mythical_unformatted,
        String ultrabeast,
        String ultrabeast_unformatted,
        String paradox,
        String paradox_unformatted,
        String hidden_ability,
        String hidden_ability_unformatted,
        String bucket,
        String bucket_unformatted,
        String common,
        String uncommon,
        String rare,
        String ultra_rare
) {
    public static MessageTemplates createDefault() {
        return new MessageTemplates(
                new String[]{
                        "This config is only on your client. It determines how each piece of an alert is displayed, giving you full control over displaying them.",
                        "For documentation on using the config, please see the Modrinth or GitHub for the mod.",
                        "https://modrinth.com/mod/cobblemon-spawn-alerts",
                        "https://github.com/StainlessStasis/CobblemonSpawnAlerts"
                },
                "cobblemon-spawn-alerts.default_spawn_message",
                "cobblemon-spawn-alerts.default_despawn_message",
                "cobblemon-spawn-alerts.despawn_reason_despawned",
                "cobblemon-spawn-alerts.despawn_reason_captured",
                "cobblemon-spawn-alerts.despawn_reason_fainted",
                "cobblemon-spawn-alerts.despawn_reason_died",
                "cobblemon-spawn-alerts.shiny",
                "cobblemon-spawn-alerts.shiny_unformatted",
                "cobblemon-spawn-alerts.level",
                "cobblemon-spawn-alerts.level_hover",
                "cobblemon-spawn-alerts.level_unformatted",
                "cobblemon-spawn-alerts.ivs",
                "cobblemon-spawn-alerts.ivs_hover",
                "cobblemon-spawn-alerts.ivs_unformatted",
                "cobblemon-spawn-alerts.evs",
                "cobblemon-spawn-alerts.evs_hover",
                "cobblemon-spawn-alerts.evs_unformatted",
                "cobblemon-spawn-alerts.nature",
                "cobblemon-spawn-alerts.nature_hover",
                "cobblemon-spawn-alerts.nature_unformatted",
                "cobblemon-spawn-alerts.ability",
                "cobblemon-spawn-alerts.ability_hover",
                "cobblemon-spawn-alerts.ability_unformatted",
                "cobblemon-spawn-alerts.gender",
                "cobblemon-spawn-alerts.gender_hover",
                "cobblemon-spawn-alerts.gender_unformatted",
                "cobblemon-spawn-alerts.male",
                "cobblemon-spawn-alerts.female",
                "cobblemon-spawn-alerts.genderless",
                "cobblemon-spawn-alerts.coords",
                "cobblemon-spawn-alerts.coords_hover",
                "cobblemon-spawn-alerts.coords_unformatted",
                "cobblemon-spawn-alerts.biome",
                "cobblemon-spawn-alerts.biome_hover",
                "cobblemon-spawn-alerts.biome_unformatted",
                "cobblemon-spawn-alerts.nearest_player",
                "cobblemon-spawn-alerts.nearest_player_hover",
                "cobblemon-spawn-alerts.nearest_player_unformatted",
                "cobblemon-spawn-alerts.legendary",
                "cobblemon-spawn-alerts.legendary_unformatted",
                "cobblemon-spawn-alerts.mythical",
                "cobblemon-spawn-alerts.mythical_unformatted",
                "cobblemon-spawn-alerts.ultrabeast",
                "cobblemon-spawn-alerts.ultrabeast_unformatted",
                "cobblemon-spawn-alerts.paradox",
                "cobblemon-spawn-alerts.paradox_unformatted",
                "cobblemon-spawn-alerts.hidden_ability",
                "cobblemon-spawn-alerts.hidden_ability_unformatted",
                "cobblemon-spawn-alerts.bucket",
                "cobblemon-spawn-alerts.bucket_unformatted",
                "cobblemon-spawn-alerts.common",
                "cobblemon-spawn-alerts.uncommon",
                "cobblemon-spawn-alerts.rare",
                "cobblemon-spawn-alerts.ultra_rare"
        );
    }
}
