modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
# neo doesnt like dashes so yeah
modId = "cobblemon_spawn_alerts"
version = "${version}"
displayName = "CobblemonSpawnAlerts"
authors = "Stasis, the Shattered"
description = '''
A highly customizable sidemod for Cobblemon 1.7.0+ to alert you when a certain Pokemon spawns
'''
logoFile = "assets/cobblemon-spawn-alerts/icon.png"

[[dependencies.cobblemon_spawn_alerts]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_spawn_alerts]]
modId = "neoforge"
mandatory = true
versionRange = "[21.1.182,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_spawn_alerts]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.7.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_spawn_alerts]]
modId = "emberstextapi"
mandatory = true
versionRange = "[2.5.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cobblemon_spawn_alerts]]
modId = "yet_another_config_lib_v3"
mandatory = false
versionRange = "[3.8.0,)"
ordering = "AFTER"
side = "CLIENT"

[[mixins]]
config="common.mixins.json"
[[mixins]]
config="neo.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"
